// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManilaProvisioner) DeepCopyInto(out *ManilaProvisioner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManilaProvisioner.
func (in *ManilaProvisioner) DeepCopy() *ManilaProvisioner {
	if in == nil {
		return nil
	}
	out := new(ManilaProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManilaProvisioner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManilaProvisionerList) DeepCopyInto(out *ManilaProvisionerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManilaProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManilaProvisionerList.
func (in *ManilaProvisionerList) DeepCopy() *ManilaProvisionerList {
	if in == nil {
		return nil
	}
	out := new(ManilaProvisionerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManilaProvisionerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManilaProvisionerSpec) DeepCopyInto(out *ManilaProvisionerSpec) {
	*out = *in
	out.OperatorSpec = in.OperatorSpec
	if in.ReclaimPolicy != nil {
		in, out := &in.ReclaimPolicy, &out.ReclaimPolicy
		*out = new(v1.PersistentVolumeReclaimPolicy)
		**out = **in
	}
	out.OpenStackSecrets = in.OpenStackSecrets
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OsSecretNamespace != nil {
		in, out := &in.OsSecretNamespace, &out.OsSecretNamespace
		*out = new(string)
		**out = **in
	}
	if in.ShareSecretNamespace != nil {
		in, out := &in.ShareSecretNamespace, &out.ShareSecretNamespace
		*out = new(string)
		**out = **in
	}
	if in.OsShareID != nil {
		in, out := &in.OsShareID, &out.OsShareID
		*out = new(string)
		**out = **in
	}
	if in.OsShareName != nil {
		in, out := &in.OsShareName, &out.OsShareName
		*out = new(string)
		**out = **in
	}
	if in.OsShareAccessID != nil {
		in, out := &in.OsShareAccessID, &out.OsShareAccessID
		*out = new(string)
		**out = **in
	}
	if in.CSIDriver != nil {
		in, out := &in.CSIDriver, &out.CSIDriver
		*out = new(string)
		**out = **in
	}
	if in.Mounter != nil {
		in, out := &in.Mounter, &out.Mounter
		*out = new(string)
		**out = **in
	}
	if in.NFSShareClient != nil {
		in, out := &in.NFSShareClient, &out.NFSShareClient
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManilaProvisionerSpec.
func (in *ManilaProvisionerSpec) DeepCopy() *ManilaProvisionerSpec {
	if in == nil {
		return nil
	}
	out := new(ManilaProvisionerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManilaProvisionerStatus) DeepCopyInto(out *ManilaProvisionerStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManilaProvisionerStatus.
func (in *ManilaProvisionerStatus) DeepCopy() *ManilaProvisionerStatus {
	if in == nil {
		return nil
	}
	out := new(ManilaProvisionerStatus)
	in.DeepCopyInto(out)
	return out
}
